### ISSUE TITLE
'codecept run' doesn`t work

### ISSUE THREAD

**Issue by andrewdonskikh** [mikeerickson/gulp-codeception#3]
"codecept run" from readme doesn`t work  - it trying to find "run" suit and fals with exception

 [RuntimeException]
  Suite 'run' could not be found

**Comment by mikeerickson** [comment]
@andrewdonskikh Can you please see if 'codecept run' works from terminal.

**Comment by andrewdonskikh** [comment]
Hello Mike! Yes sure it does. And your plugin works perfectly if I write - '.pipe(codecept('./vendor/bin/codecept', options));'. It`s very helpful thank you! Only strange behaviour with 'run'
